# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DHqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2, imutils
import numpy as np
from numpy.fft import fft2, fftshift, ifft2
import matplotlib.pyplot as plt

l_wave = 635e-9 #ความยาวคลื่นของแสง
deltax = 11.6e-6
deltay = 11.6e-6

# ขนาดภาพ (pixels)
M = 1728
N = 1152

deltafx = 1 / (M * deltax)
deltafy = 1 / (N * deltay)
k = 2 * np.pi / l_wave
x = np.linspace(1, M, M)
y = np.linspace(1, N, N)
X, Y = np.meshgrid(x, y)
M1 = (M / 2) - 1
N1 = (N / 2) - 1
X1 = l_wave * deltafx
Y1 = l_wave * deltafy
position_x = np.subtract(X, M1)
position_y = np.subtract(Y, N1)
axis_x = np.power(np.multiply(position_x, X1), 2)
axis_y = np.power(np.multiply(position_y, Y1), 2)
gamma = np.power(np.subtract(1, np.subtract(axis_x, axis_y)), 0.5)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """ ฟังก์ชันกำหนดค่าเริ่มต้น UI เช่น ขนาด ตำแหน่ง ฟอนต์ และลักษณะของปุ่ม """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 10, 791, 671))
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("../PJ test/T.jpg"))
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 690, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(230, 690, 601, 31))

        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 728, 289, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(140, 690, 81, 31))

        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(919, 630, 55, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(839, 630, 61, 31))
        self.label_6.setObjectName("label_6")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(849, 149, 41, 441))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setMinimum(-255)

        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(919, 149, 41, 441))
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_2.setMaximum(127)
        self.verticalSlider_2.setMinimum(-127)

        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(850, 600, 41, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setMinimum(-255)

        self.spinBox_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_5.setGeometry(QtCore.QRect(920, 600, 41, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_5.setMaximum(127)
        self.spinBox_5.setMinimum(-127)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 680, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(850, 20, 111, 111))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 720, 231, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 50, 71, 21))
        self.spinBox_2.setMaximum(10000)

        self.spinBox_2.setObjectName("spinBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(130, 25, 71, 21))
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_3.setMinimum(-10000)

        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(110, 40, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 730, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(850, 780, 121, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 720, 221, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Setup การเชื่อมต่อการทำงานของปุ่ม
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.loadImage)
        self.pushButton_2.clicked.connect(self.savePhoto)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.horizontalSlider.sliderMoved['int'].connect(self.spinBox.setValue)
        self.horizontalSlider.valueChanged['int'].connect(self.reconstuction_value)
        self.spinBox_2.valueChanged['int'].connect(self.horizontalSlider.setMaximum)
        self.spinBox_2.valueChanged['int'].connect(self.spinBox.setMaximum)
        self.spinBox_3.valueChanged['int'].connect(self.spinBox.setMinimum)
        self.spinBox_3.valueChanged['int'].connect(self.horizontalSlider.setMinimum)
        self.pushButton_3.clicked.connect(self.resetImage)
        self.pushButton_4.clicked.connect(self.ShowImg)
        self.verticalSlider.valueChanged['int'].connect(self.brightness_value)
        self.verticalSlider_2.valueChanged['int'].connect(self.contrast_img)
        self.spinBox_4.valueChanged['int'].connect(self.verticalSlider.setValue)
        self.verticalSlider.sliderMoved['int'].connect(self.spinBox_4.setValue)
        self.spinBox_5.valueChanged['int'].connect(self.contrast_img)
        self.verticalSlider_2.sliderMoved['int'].connect(self.spinBox_5.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # added code value
        self.filename = None
        self.tmp = None
        self.Recon_z = 0
        self.contrast_img_now = 0
        self.brightness_value_now = 0

    def loadImage(self):
        """ เป็นฟังก์ชันโหลดรูปที่ผู้ใช้เลือก และตั้งชื่อ label โดยใช้ฟังชั่น setPhoto """
        self.filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        self.image = cv2.imread(self.filename, cv2.IMREAD_GRAYSCALE)
        self.setPhoto(self.image)

    def setPhoto(self, image):
        """ ฟังก์ชั่นนี้จะรับ input ของรูป และปรับขนาด เพื่อใช้แสดงผล และแปลงเป็น QImage เพื่อตั้งค่า Label """
        self.tmp = image
        image = imutils.resize(image, width=640)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)
        self.label1.setPixmap(QtGui.QPixmap.fromImage(image))

    def reconstuction_value(self, value):
        """ ฟังก์ชันแบบเลื่อนปรับค่า z """
        self.Recon_z = value
        self.update()

    def changeReconstuction(self, img, value):
        """ ฟังก์ชันในการสร้างภาพใหม่ """
        Fz = np.exp(-1j * value * k * gamma /1000)
        FFT = fftshift(fft2(fftshift(img)))
        IFFT = fftshift(ifft2(fftshift(FFT * Fz)))
        IFFT = np.abs(IFFT)
        img = np.asarray(IFFT, dtype=np.uint8)
        return img

    def update(self):
        """ ฟังก์ชันอัพเดทภาพตาม filter """
        img = self.changeReconstuction(self.image, self.Recon_z)
        img = self.changeBrightness(img, self.brightness_value_now)
        img = self.changeContrast(img, self.contrast_img_now)
        self.setPhoto(img)

    def savePhoto(self):
        """ ฟังก์ชัน Save รูปภาพ """
        self.filename = QFileDialog.getSaveFileName(filter="Image (*.*)")[0]
        cv2.imwrite(self.filename, self.tmp)

    def contrast_img(self, value):
        """ ฟังก์ชันเรียกใช้การปรับคอนทราสของภาพ """
        self.contrast_img_now = value
        self.update()

    def brightness_value(self, value):
        """ ฟังก์ชันเรียกใช้การปรับค่าความสว่าง """
        self.brightness_value_now = value
        self.update()

    def changeBrightness(self, img, value):
        """ ฟังก์ชัน setup สมการการปรับความสว่าง """
        brightness = value
        if brightness != 0:
            if brightness > 0:
                shadow = brightness
                highlight = 255
            else:
                shadow = 0
                highlight = 255 + brightness
            alpha_b = (highlight - shadow) / 255
            gamma_b = shadow
            img = cv2.addWeighted(img, alpha_b, img, 0, gamma_b)
        return img

    def changeContrast(self, img, value):
        """ ฟังก์ชัน setup สมการการปรับค่าคอนทราสของภาพ """
        contrast = value
        if contrast != 0:
            f = float(131 * (contrast + 127)) / (127 * (131 - contrast))
            alpha_c = f
            gamma_c = 127 * (1 - f)
            img = cv2.addWeighted(img, alpha_c, img, 0, gamma_c)
        return img

    def resetImage(self, img):
        """ ฟังก์ชัน reset ค่า filter ของภาพ """
        pass

    def ShowImg(self, img):
        """ ฟังก์ชันเรียกใช้การแสดงผลรูปผ่าน matplotlib """
        img = self.changeReconstuction(self.image, self.Recon_z)
        img = self.changeBrightness(img, self.brightness_value_now)
        img = self.changeContrast(img, self.contrast_img_now)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.imshow(img)
        plt.show()

    def setTools(self):
        """ ฟังก์ชันเรียกใช้เครื่องมืออื่นๆ """
        pass

    def ImgMode(self, img):
        """ ฟงก์ชันเรียกใช้โหมดการสร้างภาพใหม่ """
        pass


    def retranslateUi(self, MainWindow):
        """ ฟังก์ชันการกำหนดชื่อ UI """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Z position (mm) "))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.pushButton_2.setText(_translate("MainWindow", "save"))
        self.label_5.setText(_translate("MainWindow", "Contrast"))
        self.label_6.setText(_translate("MainWindow", "Brigthness"))
        self.pushButton_3.setText(_translate("MainWindow", "Reset"))
        self.groupBox.setTitle(_translate("MainWindow", "Image Mode"))
        self.radioButton.setText(_translate("MainWindow", "Phase"))
        self.radioButton_2.setText(_translate("MainWindow", "Ampitude"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Z boundary"))
        self.label_4.setText(_translate("MainWindow", "maximum Z"))
        self.label_3.setText(_translate("MainWindow", "minimum Z"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.pushButton_4.setText(_translate("MainWindow", "Show Image"))
        self.pushButton_5.setText(_translate("MainWindow", "Tools"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reconstruction Image v3.1"))
        self.label_7.setText(_translate("MainWindow", "By Patthapon Nilkrom"))
        self.label_8.setText(_translate("MainWindow", "Contact: 63605033@kmitl.ac.th"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
